### ISSUE TITLE
IDEA: Compatibility with CC:Tweaked (ComputerCraft)

### ISSUE THREAD

**Issue by vico93** [Drathonix/LoadMyChunks#3] opened 2024-06-16 02:06 UTC
Hello!

I use [CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked) ([Modrinth](https://modrinth.com/mod/cc-tweaked)) (fork of ComputerCraft for modern MC versions) in my modpack, but unfortunately by design computers and [turtles](https://tweaked.cc/module/turtle.html) (robots) cannot keep the chunks they are in or the ones that they are heading to, what greatly dimishes the automation potential for them.

Could you make an integration with CC:T's API to allow turtles to equip the mod's Chunk Loader block and interact with them? While the way to allow a certain item/block to be able to be equipped by a turtle is via data-driven `.json` files ([example for regular tools](https://datapacks.madefor.cc/)), to add special funcionality (in this case, chunk loading), code is needed to make it work.

**Comment by Drathonix** [comment] 2024-06-21 14:30
I like this idea. Anyways, scuffed way to do this currently would be to use turtles to place and break chunk loaders as they move, probably too complicated to be worth it though.

It'd be useful for me to know what MC version you're currently playing on. I'll try pushing an update to all available versions with CC:T as well as any future versions but I'll prioritize yours for the purposes of faster delivery.

**Comment by vico93** [comment] 2024-06-21 15:20
> I like this idea. Anyways, scuffed way to do this currently would be to use turtles to place and break chunk loaders as they move, probably too complicated to be worth it though.
> 
> It'd be useful for me to know what MC version you're currently playing on. I'll try pushing an update to all available versions with CC:T as well as any future versions but I'll prioritize yours for the purposes of faster delivery.

Currently i'm on 1.21, just waiting for @SquidDev to finish his update to CC:T

**Comment by Drathonix** [comment] 2024-06-21 16:45
> Currently i'm on 1.21, just waiting for @SquidDev to finish his update to CC:T

I'll dev it for 1.20.4 for the time being (given that's when CC:T switched to neo)

I'll make sure to watch CC:T for updates.

**Comment by Drathonix** [comment] 2024-06-21 17:47
Putting this here so that I don't miss a feature.

| Feature                                                          | Description                                                                                                                                                                  | Done |
|------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|
| Add Lagometer block and expose to comparators and peripheral     | Figure we might as well have a non-chunk loader way to measure chunk lag and use it for world interaction. Maybe you'd want to have some sort of screen showing a lag meter. | ✅    |
| Add "getChunkLastTickDuration()" function                        | Returns chunk's last time in MS tick time.                                                                                                                                   | ✅    |
| Add "getChunkTickDurationLimit()" function                       | Returns the server side chunk tick time limit.                                                                                                                               | ✅ |
| Add "getChunkLastTickRatio()" function                               | Returns getChunkLastTickDuration()/getChunkTickDurationLimit() range of [0-1].                                                                                               | ✅  |
| Add "getChunkCooldownTime() function                             | Returns the time left in a chunk's cooldown.                                                                                                                                 | ✅  |
| Add "isChunkOnCooldown() function                                | Returns if the chunk is in cooldown.                                                                                                                                         | ✅  |
| Add "isChunkForced() function                                    | Returns if the chunk is force loaded.                                                                                                                                        |  ✅  |
| Expose Chunk Loader blocks as a peripheral                       | Expose Chunk Loader blocks as a peripheral                                                                                                                                   | ✅  |
| Chunk Loader peripheral extends lagometer                        | Allows using lagometer functions in the chunkloader                                                                                                                          | ✅  |
| Add "setActive(boolean)" function                                | Sets whether or not the chunk loader will *try* to load the chunk                                                                                                            | ✅|
| Add "activate()" function                                        | Macro for setActive(true)                                                                                                                                                    | ✅|
| Add "deactivate()" function                                      | Macro for setActive(false)                                                                                                                                                   | ✅|
| Add "isActive()" function                                        | Returns if the chunk loader is trying to load the chunk                                                                                                                      | ✅|
| Add "toggleActive()" function                                    | Macro for setActive(!isActive())                                                                                                                                             | ✅|
| Add "getOwnerName()" function                                    | Returns the chunkloader owner's name, can be nil.                                                                                                                            | ✅|
| Add "getOwnerUUID()" function                                    | Returns the chunkloader owner's UUID, can be nil.                                                                                                                            | ✅|
| Allow Chunkloaders to be attachable to turtles                   | Will load the chunk it is currently in and the destination if applicable                                                                                                                                    | ✅|
| Add Config value for disabling the lagometer peripheral features | Should support banning the lagometer methods in turtles only and/or in computers (I.E. using create to make a base hunting machine)                                          | ✅|

**Comment by vico93** [comment] 2024-06-23 17:30
@Drathonix just to let you know that [a release for 1.21](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.21-1.111.0) just got dropped!

**Comment by Drathonix** [comment] 2024-06-23 18:54
> @Drathonix just to let you know that [a release for 1.21](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.21-1.111.0) just got dropped!

Thanks for informing, I'll make sure to include CCT support in 1.0.4 then.

**Comment by Drathonix** [comment] 2024-06-23 20:15
> > @Drathonix just to let you know that [a release for 1.21](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.21-1.111.0) just got dropped!
> 
> Thanks for informing, I'll make sure to include CCT support in 1.0.4 then.

- Meant 1.0.5, 1.0.4 will be mostly a test of the new stonecutter build and I'd rather not have CCT code in the mix to cause issues.

**Comment by Drathonix** [comment] 2024-06-25 02:23
@vico93 

I have released a beta version for MC 1.21 on CF and MR for both Neoforge and Fabric. with all the requirements I listed earlier, I'd appreciate if you tried it out!

Issue will be closed once functionality is fully backported to all currently supported MC vers.

**Comment by vico93** [comment] 2024-06-25 11:37
> @vico93
> 
> I have released a beta version for MC 1.21 on CF and MR for both Neoforge and Fabric. with all the requirements I listed earlier, I'd appreciate if you tried it out!
> 
> Issue will be closed once functionality is fully backported to all currently supported MC vers.

will test asap!

**Comment by vico93** [comment] 2024-06-25 11:55
Er.. tried to drop the latest release on modrinth to my modpack, when i tried to load an existing world, this happened
[crash-2024-06-25_08.53.49-server.txt](https://github.com/user-attachments/files/15970445/crash-2024-06-25_08.53.49-server.txt)

**Comment by Drathonix** [comment] 2024-06-25 14:59
> Er.. tried to drop the latest release on modrinth to my modpack, when i tried to load an existing world, this happened [crash-2024-06-25_08.53.49-server.txt](https://github.com/user-attachments/files/15970445/crash-2024-06-25_08.53.49-server.txt)

Literally never seen this error before, as far as I can tell its an issue with the library itself.

I might be able to diagnose the problem if you send me a file from your world directory. Send me the file "loadmychunks_manager.dat" in saves/<world>/data. You may also want to try deleting this file and starting the world, just chunk loaders will lose ownership, but that has no impact on gameplay right now and you can fix them by breaking and replacing.

**Comment by vico93** [comment] 2024-06-25 16:04
er... this file doesn't exist in the data directory of the world i tried to load the mod with
![image](https://github.com/Drathonix/LoadMyChunks/assets/3485505/35de2366-af3d-4447-998c-e82cce7fa877)

**Comment by Drathonix** [comment] 2024-06-25 16:06
> er... this file doesn't exist in the data directory of the world i tried to load the mod with ![image](https://private-user-images.githubusercontent.com/3485505/342806799-35de2366-af3d-4447-998c-e82cce7fa877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzE3NzEsIm5iZiI6MTcxOTMzMTQ3MSwicGF0aCI6Ii8zNDg1NTA1LzM0MjgwNjc5OS0zNWRlMjM2Ni1hZjNkLTQ0NDctOTk4Yy1lODJjY2U3ZmE4NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTYwNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc2ZDlmYWU4OTc4ZDZmNGNhMmEzOTRlYTZhOGQwZDUyZmM1NTZkYjkzN2U1YTM1MTkwZWFkMWNiNDY5Y2Y5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ex95FuSaMfeiAhCdDEdHCiA1MQuTJZ-GdD3NQp0kaH8)

Have you never placed any chunk loaders in that world then?

**Comment by Drathonix** [comment] 2024-06-25 16:08
Possibly related to https://github.com/vigna/fastutil/issues/42, likely caused by chunks being loaded on a different thread.

Will solve with a solution similar to: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/commit/9160005d31de4749fa9a4d72d090b55ed605d2c9

@vico93 

What other mods do you have installed? (EDIT: nvm they're in the crash report)

**Comment by Drathonix** [comment] 2024-06-25 16:12
@vico93 
Cause is likely a conflict with: https://www.curseforge.com/minecraft/mc-mods/c2me-fabric

I will need to find a fix for this but for now your only option is to either disable my mod or disable CCME.

**Comment by Drathonix** [comment] 2024-06-25 17:33
@vico93 I haven't been able to replicate the problem on my system, but I am confident that the I have mod I have provided in the zip here will fix your crashing problem. Make sure c2me is enabled.

[loadmychunks-1.0.5-alpha2+1.21+fabric.zip](https://github.com/user-attachments/files/15975423/loadmychunks-1.0.5-alpha2%2B1.21%2Bfabric.zip)

**Comment by vico93** [comment] 2024-06-25 19:46
> @vico93 Cause is likely a conflict with: https://www.curseforge.com/minecraft/mc-mods/c2me-fabric
> 
> I will need to find a fix for this but for now your only option is to either disable my mod or disable CCME.

Hm i see. Maybe @ishland (c2me author) could give some insight about this.

**Comment by vico93** [comment] 2024-06-25 19:46
> @vico93 I haven't been able to replicate the problem on my system, but I am confident that the I have mod I have provided in the zip here will fix your crashing problem. Make sure c2me is enabled.
> 
> [loadmychunks-1.0.5-alpha2+1.21+fabric.zip](https://github.com/user-attachments/files/15975423/loadmychunks-1.0.5-alpha2%2B1.21%2Bfabric.zip)

sorry, didnt saw this comment. Do you want my profile folder for better testing? Can zip it and send to you

**Comment by Drathonix** [comment] 2024-06-25 20:19
> > @vico93 I haven't been able to replicate the problem on my system, but I am confident that the I have mod I have provided in the zip here will fix your crashing problem. Make sure c2me is enabled.
> > [loadmychunks-1.0.5-alpha2+1.21+fabric.zip](https://github.com/user-attachments/files/15975423/loadmychunks-1.0.5-alpha2%2B1.21%2Bfabric.zip)
> 
> sorry, didnt saw this comment. Do you want my profile folder for better testing? Can zip it and send to you

I replicated your modpack nearly exactly, the only difference between us is CPU and JVM brand, which are both things I can't control. See if the file I provided there solves the problem with C2ME and report back.

**Comment by vico93** [comment] 2024-06-25 21:07
Didnt crash this time. I still need to test the mod's features. Thanks!

**Comment by vico93** [comment] 2024-06-25 21:14
Just noticed that, after installing LoadMyChunks, the movement of my turtle become accelerated and choppy.

Without the mod it was more fluid and slower.

https://github.com/Drathonix/LoadMyChunks/assets/3485505/c9539382-6df3-47d4-abd7-286ca3daace8

**Comment by vico93** [comment] 2024-06-25 21:18
Without the mod, for reference

https://github.com/Drathonix/LoadMyChunks/assets/3485505/26ac1c8e-5105-4c34-a9ab-2d02711eb4ac

**Comment by Drathonix** [comment] 2024-06-25 21:32
> Just noticed that, after installing LoadMyChunks, the movement of my turtle become accelerated and choppy.
> 
> Without the mod it was more fluid and slower.
> 
>  Minecraft_.1.21.-.Um.jogador.2024-06-25.18-11-54-lite.mp4

Can you send me your script? There's definitely an issue here

**Comment by vico93** [comment] 2024-06-25 21:40
Here:

```lua
term.write("how Long should the tunnel be?")
local lol = read()
while turtle.getFuelLevel() < lol*7 do
 local q = turtle.getFuelLevel()
  if turtle.getFuelLevel() < lol*7 then
   term.write("Fuel Level is at "..q.." But needs to be "..lol*7)
   term.write("Please put Fuel in 1st slot")
   os.sleep(5)
   turtle.refuel()
  end
end
   term.write("Mining a "..lol.." block long tunnel")
  
   for a = 1,lol do
      turtle.dig()
      turtle.forward()
      turtle.digUp()
      turtle.digDown()
      turtle.turnRight()
      turtle.dig()
      turtle.forward()
      turtle.digUp()
      turtle.digDown()
      turtle.back()
      turtle.turnLeft()
      turtle.turnLeft()
      turtle.dig()
      turtle.forward()
      turtle.digUp()
      turtle.digDown()
      turtle.back()
      turtle.turnRight()
     end
    for b = 1,lol do
     turtle.back()
    end
   for c = 1,16 do
    turtle.select(c)
    turtle.dropDown(64)
   end
 turtle.select(1)
 
```

**Comment by Drathonix** [comment] 2024-06-25 21:53
@vico93 
I may have fixed the issue. In my game they seem to be running normally now. See if this file makes the turtles work normally on your system. If it does I'll publish to CF and MR with the fixes in place. Thanks for your cooperation!

[loadmychunks-1.0.5-alpha2+1.21+fabric.zip](https://github.com/user-attachments/files/15979720/loadmychunks-1.0.5-alpha2%2B1.21%2Bfabric.zip)

**Comment by Drathonix** [comment] 2024-06-26 02:30
@vico93 sorry to bother you like this, but I have another file I can't test on my own system that attempts to fix the C^2ME issue better. I'd appreciate if you could test this one out. Thank you.
[loadmychunks-1.0.5-alpha3+1.21+fabric.zip](https://github.com/user-attachments/files/15981574/loadmychunks-1.0.5-alpha3%2B1.21%2Bfabric.zip)

**Comment by vico93** [comment] 2024-06-26 11:35
will test and get back to you

**Comment by vico93** [comment] 2024-06-26 12:04
I still didnt tested the turtles, but i already noticed that regular furnaces are burning items **very** fast compared to without the mod.

**Comment by Drathonix** [comment] 2024-06-26 12:25
> I still didnt tested the turtles, but i already noticed that regular furnaces are burning items **very** fast compared to without the mod.

You are right. Block Entities are actually ticking 2 times faster in your pack (which is also why the turtles were moving at 2x speed).

Its not a problem with LMC at base though, so its another mod conflict that I have to find. Good news is that C^2ME didn't crash you though so that's all good.  I'll open a separate issue for the block entity 2x speed problem.

**Comment by Drathonix** [comment] 2024-06-26 13:43
Cause is not a mod conflict, but a mixin issue. The bug will mostly just affect recently placed block entities. I'll get a patch out by the end of the day.

**Comment by Drathonix** [comment] 2024-06-26 15:03
Published an Alpha file on MR and CF that should be stable now. Will close multiple relevant issues once 1.0.5 release is published.

**Comment by vico93** [comment] 2024-06-27 14:09
@Drathonix with the same code i send above, i got an error when i made a turtle finished placing the items on the chest:

[crash-2024-06-27_11.07.58-server.txt](https://github.com/user-attachments/files/16015354/crash-2024-06-27_11.07.58-server.txt)

**Comment by Drathonix** [comment] 2024-06-27 15:26
> @Drathonix with the same code i send above, i got an error when i made a turtle finished placing the items on the chest:
> 
> [crash-2024-06-27_11.07.58-server.txt](https://github.com/user-attachments/files/16015354/crash-2024-06-27_11.07.58-server.txt)

Likely just another incompatibility with C^2ME, its a very easy patch though so not worth reporting on my side. I'll get the release out today.

**Comment by Drathonix** [comment] 2024-06-28 00:14
Released in 1.0.5

**Closed as completed by Drathonix** 2024-06-28 00:14 UTC
Labels: feature, accepted, high priority

**Comment by SquidDev** [comment] 2024-07-01 15:34
Just checking out your implementation of this, and wanted to check why you needed to mixin to CC's code here? I'd really rather people avoid this as it's a compatibility (and debugging) nightmare, and instead let me know if there's any additional API hooks that might be useful.

At least please, please, please don't `@Overwrite` other mods' methods. You can definitely do that with a more targeted `@Redirect`/`@WrapOperation`.

**Comment by Drathonix** [comment] 2024-07-01 16:14
> Just checking out your implementation of this, and wanted to check why you needed to mixin to CC's code here? I'd really rather people avoid this as it's a compatibility (and debugging) nightmare, and instead let me know if there's any additional API hooks that might be useful.
> 
> At least please, please, please don't `@Overwrite` other mods' methods. You can definitely do that with a more targeted `@Redirect`/`@WrapOperation`.

The @Overwrite was admittedly out of laziness. I had previously used an @Redirect there but removed it at some point attempting to debug the nonsensical mixin hell caused by 'remap' having an episode of multiple personality disorder. In future versions of the mod I'll rewrite this mixin with @Redirect or remove it altogether depending on your thoughts on the API requirements.

There are a few missing things in the CC:T API that need to exist for moving chunk loaders to actually work, I'll go over the problems here.

1. Upgrade/peripheral instances do not get notified when they are removed from the turtle, definitely a worthy of being an API feature. I needed to do this to detect when to remove the turtle chunk loader from the LMC chunk data manager. (Seen in MixinTileTurtle and MixinTurtleBrain)

2. Upgrade/peripheral instances do not get notified when a turtle changes its position, again something essential for LMC given it needs to keep track of the turtle's chunk position. I recommend having some sort of premove and postmove method in the upgrade or peripheral class.

3. Turtles always do the level.isLoaded check before moving, which needs to be cancelled by LMC. The API implementation would need to allow upgrade/peripheral instances to cancel specific movement checks and possibly even do its own for completeness sake. Likely would be a part of the premove method I guess.

I have been using mixins for years now, its my responsibility to make them work, and it is indeed a debugging nightmare when you have to deal with multiple modloaders and MC versions. However, it seems highly unlikely to me that the code will ever change significantly. Ironically it was actually the API that changed the most between 1.16.5 and 1.21, which of course makes sense but my point is that there was much more tedium from having to account for API changes than there was from having to tweak the mixin. Of course the real concern is when some other CC:T integrated mod comes out and mixins the move command and causes a conflict, and I can definitely envision some cases where hooking into the move command would be useful to a dev other than this case.

**Comment by SquidDev** [comment] 2024-07-02 09:47
> Upgrade/peripheral instances do not get notified when they are removed from the turtle

So the upgrade's peripheral will have `IPeripheral.detach` called on it when the upgrade is removed or the turtle shut down (which I feel should also stop chunk loading). Does that work for what you need?

> Upgrade/peripheral instances do not get notified when a turtle changes its position [...]

`ITurtleUpgrade.upgrade` is called very tick (after commands have been processed), which can be used to handle the post-move logic. This is definitely worth doing anyway, to account for mods which move turtles in other ways (such as AdvancedPeripherals's warping upgrade).

As far as the pre-move checks, and `isLoaded` in the move command, that is a bit trickier, and probably does require a mixin and/or an API change.

I'm afraid my knowledge of chunk loaders is a bit rusty here, so bear with me. My understanding is that every ticking chunk kept the surrounding 3x3 also loaded (albeit at a lower ticket level). I'm assuming that's not the case though, at least within LMC?

> I have been using mixins for years now, its my responsibility to make them work

I think the trouble is that it's not always obvious to end users (or modders!) where the problem is coming from, especially on Fabric where there's not the same audit trail for core mods. I've wasted quite a lot of time in the past debugging issues caused by mods mixing-in to CC:T, so am always wary when I see more mixins crop up!

That's not to say that there aren't valid use-cases for mixins or anything! It's just useful to have  a heads-up, so I a) can be careful when touching this code in the future and b) know what to look out for if I get a bug report.

**Comment by vico93** [comment] 2024-07-21 16:04
any news? @Drathonix

**Comment by Drathonix** [comment] 2024-07-21 16:07
> any news? @Drathonix

I've been busy with other stuff so I haven't really had time to respond to squid, but his response changes nothing about the current working version of LMC with CCT. The project has been completed weeks ago and it will only need updates should CC:T change the code i've targeted with mixins. I just have to be vigilant about CCT updates.

**Comment by vico93** [comment] 2024-07-21 16:09
> > any news? @Drathonix
> 
> I've been busy with other stuff so I haven't really had time to respond to squid, but his response changes nothing about the current working version of LMC with CCT. The project has been completed weeks ago and it will only need updates should CC:T change the code i've targeted with mixins. I just have to be vigilant about CCT updates.

Don't know. I restrain myself to use LMC due to fear that it could break my turtles in my server...

**Comment by SquidDev** [comment] 2024-07-21 16:12
It's not going to break turtles. The code works — it's not ideal, but not going to cause any actual functionality issues.

**Comment by Drathonix** [comment] 2024-07-21 16:26
SquidDev already responded and he is right but I want to at least explain why mixining CC:T was necessary and why it would be unlikely to break your game or corrupt the world at any point in the future.

In order for LMC to work properly, it has to know when the turtle is about to move and when it has moved so that it can move the turtle chunk loader. That required making a mixin for the Turtle Move Command. Even if someone else's mixins were to conflict with mine it wouldn't cause any irreversible damage to your world unless you had something like Neruina installed with corrupted block entity removal enabled. At the very most it would crash your game and at that point, as I've made very clear by this point, I'd gladly fix the issue. Currently no issues have arisen.

The other mixins I added to ensure that the turtle chunk loader would not continue to exist either when: it was removed from the turtle's item slot or when the turtle was destroyed. These mixins are relatively harmless and the only plausible way they could cause issues is if CC:T changes in a future version. Which again, I can patch that problem should it occur.

To reiterate, your turtles will not break and your world will not corrupt with *just* LMC and CCT. Should another mod's mixins conflict with mine, then you'd have issues, but again: highly unlikely they will.

I will try to restructure the code to use more API functions in the future but as of now that is not a priority for me especially since its currently unnecessary.

**Comment by vico93** [comment] 2024-07-22 02:18
> To reiterate, your turtles will not break and your world will not corrupt with _just_ LMC and CCT

I mean stuff like #19....

**Comment by Drathonix** [comment] 2024-07-22 03:46
> > To reiterate, your turtles will not break and your world will not corrupt with _just_ LMC and CCT
> 
> I mean stuff like #19....

Not an issue with CC:T integ, likely a problem with C^2ME. Your system definitely handles multithreading differently from mine and as such you are victim to desync issues I can't detect personally.
